### ISSUE TITLE
change reuse factor

### ISSUE THREAD

**Issue by alima1234** [emilbjornson/is-massive-MIMO-the-answer#1]
How to change the reuse factor to 3 and 7 and test the network throughput

**Comment by Kurdenes21** [comment]
Kurdenes21ç

**Comment by Kurdenes21** [comment]
Thanks

**Comment by Kurdenes21** [comment]
Thanks

**Comment by Kurdenes21** [comment]
Hi

**Comment by Kurdenes21** [comment]
#1

**Comment by emilbjornson** [comment]
@alima1234 : We are considering square cells, so then 1, 2, 4 are reuse factors that lead to symmetric patterns. Reuse factors 1, 3, 4, 7, ... lead to symmetric patterns when having hexagonal cells. There is no easy way to include that in this code.

**Comment by Kurdenes21** [comment]
#1
